name: Deploy to Production

on:
  push:
    tags:
    - 'v*'

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Aftman
      uses: ok-nick/setup-aftman@v0.4.2

    - run: rojo build -o ci-cd-pipeline-test.rbxl

    - run: rbxcloud experience publish --filename Compound-Orion.rbxl --place-id 70409779519095 --universe-id 6629397671 --version-type published --api-key ${{ secrets.API_KEY }}